version: "3"

services: 
  elasticsearch:
    image: elasticsearch:7.6.2
    container_name: elasticsearch
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - elk-network

  logstash:
    image: logstash:7.6.2
    container_name: logstash
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - elk-network
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.6.2
    container_name: kibana
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - elk-network
    depends_on:
      - elasticsearch

  nopcommerce_web:
    image: nopcommerceteam/nopcommerce
    container_name: nopcommerce
    ports:
      - 80:80
    depends_on:
      - mssql_database
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

  mssql_database:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql_database
    environment:
     SA_PASSWORD: "Smart_57903"
     ACCEPT_EULA: "Y"
     MSSQL_PID: "Express"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"

networks: 
  elk-network:
    driver: bridge
